SoftServeCarMobile/api-service/brand-service/BrandService.tsx, SoftServeCarMobile/api-service/car-service/CarService.tsx, SoftServeCarMobile/api-service/chat-service/ChatService.tsx, SoftServeCarMobile/api-service/login-service/LoginService.tsx, SoftServeCarMobile/api-service/model-service/ModelService.tsx, SoftServeCarMobile/api-service/preferences-service/PreferencesService.tsx, SoftServeCarMobile/api-service/user-service/UserService.tsx
=> Changed http request routes according to rest conventions

SoftServeCarMobile/package-lock.json, SoftServeCarMobile/package.json, SoftServeCarMobile/src/activity/journey/JourneyTabs.tsx, SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/JourneyPage.tsx, SoftServeCarMobile/src/components/BottomPopup/BottomPopup.tsx, SoftServeCarMobile/src/components/BottomPopup/BottomPopupStyle.ts, SoftServeCarMobile/src/components/BottomPopup/MenuButton.tsx, SoftServeCarMobile/yarn.lock
=> implemented more-option-list

SoftServeCarMobile/babel.config.js, SoftServeCarMobile/environment.tsx, SoftServeCarMobile/index.js, SoftServeCarMobile/react-native.config.js, SoftServeCarMobile/src/components/journey-new-applicant/JourneyNewApplicantStyle.tsx, SoftServeCarMobile/tsconfig.json
=> Closed #107 - Remove comments

SoftServeCarMobile/src/activity/login/Login.tsx, SoftServeCarMobile/src/activity/login/LoginStyle.tsx, SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCars.tsx, SoftServeCarMobile/src/activity/my-profile/my-profile-activity/details/Details.tsx, SoftServeCarMobile/src/activity/my-profile/my-profile-activity/details/DetailsStyle.tsx, SoftServeCarMobile/src/activity/my-profile/my-profile-activity/preferences/ChooseOptionComponent.tsx, SoftServeCarMobile/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx, SoftServeCarMobile/src/activity/my-profile/my-profile-activity/preferences/PreferencesStyle.tsx
=> Closed #141 - Change all Button components to TouchableOpacity

SoftServeCarMobile/Environment.tsx, SoftServeCarMobile/package-lock.json, SoftServeCarMobile/src/activity/messages/chat/simple-message/SimpleMessage.tsx, SoftServeCarMobile/src/activity/messages/chat/simple-message/SimpleMessageStyle.tsx, SoftServeCarMobile/src/activity/messages/messages-tabs/MessagesTabs.tsx, SoftServeCarMobile/yarn.lock
=> Added filter item

SoftServeCarMobile/package-lock.json, SoftServeCarMobile/src/activity/login/LoginStyle.tsx, SoftServeCarMobile/yarn.lock
=> Closed #146 - Fix Login page style (IOS app)

Car/src/activity/journey/JourneyStyle.tsx
=> Closed #186 - Fix Journey Segment Control Style

Car/src/activity/my-profile/my-profile-activity/cars/Cars.tsx, Car/src/activity/my-profile/my-profile-activity/details/Details.tsx, Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx, Car/src/activity/my-profile/my-profile-activity/preferences/PreferencesStyle.tsx
=> Closed #218 - Add loading indicators

Car/src/activity/journey/JourneyStartPage.tsx
=> Closes #245 - Journey page (list of journeys), combinated useeffects

Car/api-service/APIConfig.tsx, Car/api-service/Interceptor.tsx, Car/api-service/chat-service/ChatService.tsx, Car/package-lock.json, Car/package.json, Car/src/activity/messages/chat/Chat.tsx, Car/src/activity/messages/chat/ChatState.tsx, Car/src/activity/messages/chat/ChatStyle.tsx, Car/src/activity/messages/chat/simple-message/SimpleMessage.tsx, Car/src/activity/messages/chat/simple-message/SimpleMessageStyle.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/AddressBook.tsx, Car/src/components/error-alert/ErrorAlert.tsx, Car/src/components/navigation/app-tabs/AppTabs.tsx, Car/yarn.lock
=> Added message hub, styling messages

.gitignore, Car/android/local.properties
=> Closed #265 - Add local.properties to .gitignore

.husky/pre-commit, Car/package-lock.json, Car/package.json, Car/src/activity/messages/chat/Chat.tsx, Car/yarn.lock
=> Fixed message refreshing

Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
=> Closed #280 - Fix settings buttons

Car/api-service/SignalRHubConnection.tsx, Car/src/activity/messages/Messages.tsx, Car/src/activity/messages/messages-activity/chat/Chat.tsx
=> Fixed reconnection to the SignalR hub after background mode

Car/package-lock.json, Car/package.json, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPageStyle.tsx, Car/src/activity/journey/journey-activity/journey-request-page/JourneyRequestPage.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx, Car/src/components/journey-card/JourneyCard.tsx, Car/yarn.lock
=> Closed #235 - Add Request to Driver

Car/api-service/notifications-service/NotificationsService.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPageStyle.tsx, Car/src/activity/journey/journey-activity/journey-request-page/JourneyRequestPage.tsx, Car/src/activity/journey/journey-activity/journey-request-page/JourneyRequestPageStyle.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
=> Closed #310 - Add alert after a request to the driver has been sent

Car/__tests__/LoginService-test.tsx, Car/__tests__/PreferencesService-test.tsx, Car/__tests__/UserService-test.tsx, Car/api-service/APIRoutes.tsx, Car/api-service/SignalRHubConnection.tsx, Car/api-service/login-service/LoginService.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx, Car/src/activity/login/Login.tsx, Car/src/activity/messages/messages-activity/chat/Chat.tsx, Car/src/activity/messages/messages-tabs/MessagesTabs.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/AddressBook.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-tabs/AddressBookTabs.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx, Car/src/activity/my-profile/my-profile-activity/settings/settings-tabs/SettingsTabs.tsx
Close #308 
dev
ToDo
ToDo
ToDo
=> Fix code smells

Car/src/activity/messages/Messages.tsx, Car/src/activity/messages/messages-activity/chat/Chat.tsx, Car/src/components/styles/HeaderStyle.tsx
=> Fixed bugs with filter length, added button disabling

Car/__tests__/activity/messages/MessagesTabs-test.tsx, Car/__tests__/components/AppTabs-test.tsx, Car/__tests__/components/JourneyCard-test.tsx, Car/__tests__/components/JourneyCardList-test.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/messages/Messages.tsx, Car/src/activity/messages/messages-activity/chat/Chat.tsx, Car/src/activity/messages/messages-tabs/MessagesTabs.tsx, Car/src/components/bottom-popup/BottomPopupProps.tsx, Car/src/components/journey-card/JourneyCard.tsx, Car/src/components/navigation/app-tabs/AppTabs.tsx
=> Fixed time format

README.md
Changing for README.md with updates for "How to run locally instructions"
=> Editing readme.md

Car/ios/Car/Info.plist
Fixes ita-social-projects/Car-Back-End#368
=> Enabled using geolocations for IOS

Car/__tests__/activity/my-profile/CarTabs-test.tsx, Car/src/components/navigation/Routes.tsx
fixes ita-social-projects/Car-Back-End#358
=> Navigation bar icons fix

Car/__tests__/activity/my-profile/CarTabs-test.tsx, Car/__tests__/activity/my-profile/MyProfile-test.tsx, Car/src/activity/my-profile/MyProfile.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx
Fixes  ita-social-projects/Car-Back-End#363 
ToDo
ToDo
ToDo
=> Fixes   ita-social-projects/Car-Back-End#363

Car/src/activity/my-profile/my-profile-activity/details/Details.tsx
Fixes ita-social-projects/Car-Back-End#357
=> Deleted "Workspace" row

Car/__tests__/activity/messages/MessagesTabs-test.tsx, Car/src/activity/messages/messages-tabs/MessagesTabs.tsx
ita-social-projects/Car-Back-End/#352
=> Removed Ellipsis menu from the chat page

Car/src/activity/messages/messages-activity/chat/Chat.tsx
fixes ita-social-projects/Car-Back-End#371
=> changed date format in chat

Car/__tests__/activity/my-profile/Settings-test.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
Fixed ita-social-projects/Car-Back-End#356
=> Fixed avatar change panel

Car/src/components/confirm-modal/ConfirmModal.tsx, Car/src/components/confirm-modal/ConfirmModalProps.tsx, Car/src/components/confirm-modal/ConfirmModalStyle.tsx
Implemented ita-social-projects/Car-Back-End#379
=> Confirm modal

Car/__tests__/activity/my-profile/CarTabs-test.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx, Car/src/components/confirm-modal/ConfirmModal.tsx, Car/src/components/confirm-modal/ConfirmModalProps.tsx, Car/src/components/confirm-modal/ConfirmModalStyle.tsx, Car/src/components/header-remove-car-button/HeaderRemoveCarButton.tsx, Car/src/components/header-remove-car-button/HeaderRemoveCarButtonStyle.ts, Car/src/constants/Constants.tsx
closes ita-social-projects/Car-Back-End#380
=> Remove Car Confirmation

Car/__tests__/activity/journey/JourneyPage-test.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPageStyle.tsx
Fixes ita-social-projects/Car-Back-End#372
=> Fixes button alignment on journey page

Car/models/user/User.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx, Car/src/components/auth/AuthProvider.tsx, Car/src/components/avatar-logo/AvatarLogoProps.ts
fixed ita-social-projects/Car-Back-End/issues/356
=> fixed empty string in imageId field

.github/workflows/ArtifactGenerator.yml
=> Closed #366 - Fix ios build pipeline

Car/__tests__/activity/my-profile/AddCars-test.tsx, Car/__tests__/activity/my-profile/EditCars-test.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/edit-cars/EditCars.tsx, Car/src/components/car-text-input/CarTextInput.tsx, Car/src/components/car-text-input/CarTextInputProps.ts
Fixes  ita-social-projects/Car-Back-End#337
=> [ AddCars | EditCars ]Fixes wrong error message when user input invalid data in to the "Plate number" field

Car/__tests__/activity/my-profile/SetPlace-test.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-activity/add-locations/SetPlace.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/constants/Constants.tsx
Fixes ita-social-projects/Car-Back-End#263
=> Adds an error message when car photo exceeds 7 MB

Car/__tests__/activity/my-profile/AddCars-test.tsx, Car/__tests__/activity/my-profile/SetPlace-test.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx
Fixes  ita-social-projects/Car-Back-End#269
=> Changed color of button from #808080 to #B8B8B8

Car/__tests__/activity/my-profile/AddLocation-test.tsx, Car/__tests__/activity/my-profile/AddressBookTabs-test.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/AddressBook.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-activity/add-locations/AddLocation.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-activity/add-locations/AddLocationProps.ts, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-activity/add-locations/AddLocationStyle.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-tabs/AddressBookTabs.tsx, Car/src/components/location-drop-down-picker/LocationDropDownPicker.tsx, Car/src/components/location-drop-down-picker/LocationDropDownPickerProps.tsx, Car/src/components/location-drop-down-picker/LocationDropDownPickerStyle.tsx
Fixes ita-social-projects/Car-Back-End#385
=> Added inputs on the address page

Car/__tests__/activity/my-profile/Settings-test.tsx, Car/__tests__/components/HeaderLogoutButton-test.tsx, Car/package.json, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx, Car/src/components/auth/AuthProvider.tsx, Car/src/components/avatar-logo-title/AvatarLogoTitle.tsx, Car/src/components/confirm-modal/ConfirmModal.tsx, Car/src/components/confirm-modal/ConfirmModalStyle.tsx, Car/src/components/header-logout-button/HeaderLogoutButton.tsx, Car/src/constants/Constants.tsx
Added ConfimModal when User wants to logout
Changed Add/Change?Remove User photo logic
Closed ita-social-projects/Car-Back-End#32
=> Setings page

Car/__tests__/activity/my-profile/AddressBookTabs-test.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/AddressBook.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-activity/edit-locations/EditLocation.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-tabs/AddressBookTabs.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx, Car/src/components/menu-remove-address-button/RemoveAddressButton.tsx, Car/src/components/menu-remove-address-button/RemoveAddressButtonProps.ts, Car/src/components/menu-remove-address-button/RemoveAddressButtonStyle.tsx, Car/src/constants/Constants.tsx
closes ita-social-projects/Car-Back-End#43
=> Add bottom popup to remove address

Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx
Fixes ita-social-projects/Car-Back-End#344
=> Fixed navigation via "Message to all"

Car/__tests__/activity/journey/CreateJourney-test.tsx, Car/src/activity/journey/journey-activity/create-journey/AddressInputPade/AddressInputPage.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/create-journey/NewJourneyDetailsPage/NewJourneyDetailsPage.tsx, Car/src/components/confirm-modal/ConfirmModal.tsx, Car/src/components/confirm-modal/ConfirmModalProps.tsx
Closed  ita-social-projects/Car-Back-End#410
Closed  ita-social-projects/Car-Back-End#411
Closed #58
=> Added loading indicators and changed popups

Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx
Fixed ita-social-projects/Car-Back-End#415
=> Fixed resent addresses mapping

Car/__tests__/activity/journey/JourneyPage-test.tsx, Car/__tests__/api-service/ChatService-test.tsx, Car/__tests__/api-service/JourneyService-test.tsx, Car/android/app/src/main/java/com/car/MainApplication.kt, Car/android/app/src/main/java/com/car/SoftKeysModule/SoftKeysModule.java, Car/android/app/src/main/java/com/car/SoftKeysModule/SoftKeysPackage.java, Car/models/journey/CreateJourneyModel.ts, Car/models/journey/Journey.tsx, Car/models/journey/JourneyPoint.ts, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPageStyle.tsx, Car/src/constants/Constants.tsx
Closed ita-social-projects/Car-Back-End#432
=> Journey page map

Car/src/activity/journey/journey-activity/create-journey/AddressInput/AddressInput.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/create-journey/NewJourneyDetailsPage/NewJourneyDetailsPage.tsx, Car/src/constants/Constants.tsx
Fixed #395 
Fixed ita-social-projects/Car-Back-End#446
Fixed ita-social-projects/Car-Back-End#447
=> Fixed bugs

Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
Fixes ita-social-projects/Car-Back-End#468
=> Added modal closing

Car/__tests__/api-service/CarService-test.tsx, Car/api-service/car-service/CarService.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/edit-cars/EditCars.tsx
Closes  ita-social-projects/Car-Back-End#486
=> Change cars

Car/__tests__/activity/journey/JourneyTabs-test.tsx, Car/api-service/APIRoutes.tsx, Car/api-service/request-service/RequestService.tsx, Car/models/journey/Filter.tsx, Car/models/journey/Point.tsx, Car/models/request/RequestModel.tsx, Car/package-lock.json, Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyProps.tsx, Car/src/activity/journey/journey-activity/search-journey/search-results/bad-search-result/BadSearchResult.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx, Car/src/activity/notifications/NotificationComponent.tsx, Car/src/components/ride-found/RideFound.tsx, Car/src/components/ride-found/RideFoundProps.tsx, Car/yarn.lock
Closes ita-social-projects/Car-Back-End#376
Closes ita-social-projects/Car-Back-End#16
=> added ability to create ride request

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/edit-cars/EditCars.tsx
Closes  ita-social-projects/Car-Back-End#503
=> Removed photo size validation

Car/src/activity/messages/Messages.tsx
Closes ita-social-projects/Car-Back-End#509
=> changed D&T format in chats tab

Car/__tests__/activity/journey/BadSearchResult-test.tsx, Car/src/activity/journey/journey-activity/search-journey/search-results/bad-search-result/BadSearchResult.tsx
Closes ita-social-projects/Car-Back-End#499
=> Badresult page fix

Car/src/components/ride-found/RideFound.tsx, Car/src/components/ride-found/RideFoundStyle.tsx
Closes ita-social-projects/Car-Back-End#504
=> Ride created notification

.husky/pre-commit, Car/__tests__/components/JourneyCard-test.tsx, Car/__tests__/components/JourneyCardList-test.tsx, Car/src/components/journey-card/JourneyCard.tsx, Car/src/components/journey-card/JourneyCardStyle.tsx, Car/src/constants/JourneyConstants.tsx
=> Added FeeType to JourneyCard

Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
Closes ita-social-projects/Car-Back-End#515
=> added explicit conversion for json-Date

Car/__tests__/activity/my-profile/MyProfile-test.tsx, Car/src/activity/my-profile/MyProfile.tsx
Closes  ita-social-projects/Car-Back-End#528
=> Fixes capitalization error in MyProfile

Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
Fixed ita-social-projects/Car-Back-End/issues/508
=> Fixed options names

Car/__tests__/activity/login/Login-test.tsx, Car/src/activity/login/Login.tsx, Car/src/activity/login/LoginProps.ts, Car/src/components/auth/AuthProvider.tsx
Fixed ita-social-projects/Car-Back-End#407
=> Fixed bug with exiting from login process

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/edit-cars/EditCars.tsx
Closes ita-social-projects/Car-Back-End#523
=> Fixes save button

Car/src/activity/notifications/NotificationComponent.tsx, Car/src/components/notifications/journey-details-update/JourneyDetailsUpdate.tsx, Car/src/components/notifications/notification-modal-base/NotificationModalBase.tsx
To ita-social-projects/Car-Back-End/issues/502
=> Ride updated notification

Car/src/components/notifications/notification-ride-stops/NotificationRideStops.tsx, Car/src/components/notifications/passenger-withdrawal/PassengerWithdrawal.tsx
To ita-social-projects/Car-Back-End/issues/459
=> passanger withdrawal notification added

Car/api-service/Axios.tsx, Car/src/components/header-logout-button/HeaderLogoutButton.tsx, Car/src/constants/Constants.tsx
Closes ita-social-projects/Car-Back-End/issues/545
=> redirect settings

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/edit-cars/EditCars.tsx
Closes  ita-social-projects/Car-Back-End#497
=> Fixed regex

Car/__tests__/activity/journey/JourneyStartPage-test.tsx, Car/src/activity/journey/JourneyStartPage.tsx
Closes  ita-social-projects/Car-Back-End#450
=> Fixed label on front page

Car/src/components/notifications/notifications-types/ApplicationApproval.tsx
=> Added ConfirmModal for Withdrawal

Car/api-service/APIConfig.tsx
Updated API Key for Google Maps
Closes  ita-social-projects/Car-Back-End#563
=> Updated key for maps

Car/__tests__/components/AppTabs-test.tsx, Car/src/components/navigation/app-tabs/AppTabs.tsx
Closes  ita-social-projects/Car-Back-End#543
=> changed bottom tabbar style

Car/src/activity/my-profile/my-profile-activity/address-book/AddressBook.tsx, Car/src/constants/AddressConstants.tsx, Car/src/constants/JourneyConstants.tsx
To ita-social-projects/Car-Back-End/issues/514
=> Fixed Address name trimming

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/constants/CarConstants.tsx
To ita-social-projects/Car-Back-End#557
=> Added spaces to plate number

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-cars/AddCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/edit-cars/EditCars.tsx, Car/src/components/car-text-input/CarTextInput.tsx, Car/src/components/car-text-input/CarTextInputStyle.tsx
Closes ita-social-projects/Car-Back-End/issues/586
Closes ita-social-projects/Car-Back-End/issues/585
=> Fix plate number

Car/src/components/auth/AuthProvider.tsx
Changed hire date to pass validation
=> changed hire date to pass validation

Car/__tests__/activity/journey/JourneyTabs-test.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
Closes ita-social-projects/Car-Back-End/issues/592
=> fix journey details header

Car/src/activity/messages/Messages.tsx
Closes ita-social-projects/Car-Back-End/issues/580
=> fix chat warning message

Car/src/activity/messages/messages-activity/chat/Chat.tsx
Closes ita-social-projects/Car-Back-End/issues/575
=> changed deprecated clipboard

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx
=> Fix ride adding

Car/__tests__/activity/journey/JourneyStartPage-test.tsx, Car/src/activity/journey/JourneyStartPageStyle.tsx
Closes ita-social-projects/Car-Back-End#302
=> Aligned jorneys buttons

Car/src/components/dropdown-picker/JourneyCreationDropDownPickerStyle.tsx
Closes ita-social-projects/Car-Back-End#430
=> fixed missalignment in drop-down menu

Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
Closes ita-social-projects/Car-Back-End#437
=> fixed adding photo process

Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx, Car/src/components/datetime-picker/TouchableDateTimePicker.tsx, Car/src/components/journey-new-applicant/journey-new-applicant-view/JourneyNewApplicantView.tsx, Car/src/components/journey-new-applicant/route-view/RouteView.tsx
Fixed defects from comments in ita-social-projects/Car-Front-End/pull/506 and ita-social-projects/Car-Front-End/pull/503
=> Fix defects from comments

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx
Closes ita-social-projects/Car-Back-End#557
=> Updated validation message for plate number

Car/__tests__/activity/journey/JourneyStartPage-test.tsx, Car/src/activity/journey/JourneyStartPageStyle.tsx
Closes ita-social-projects/Car-Back-End#302
=> 302 manage journeys buttons arent aligned

Car/__tests__/activity/messages/Chat-test.tsx, Car/package-lock.json, Car/package.json, Car/src/activity/messages/messages-activity/chat/Chat.tsx, Car/src/activity/messages/messages-activity/chat/ChatStyle.tsx, Car/tsconfig.json, Car/yarn.lock
=> 424 chat header disapears while texting

Car/api-service/Axios.tsx
=> Code smell fixing

Car/__tests__/components/HeaderRemoveCarButton-test.tsx, Car/__tests__/components/MinimizedNotification-test.tsx, Car/__tests__/components/WithLuggage-test.tsx, Car/src/components/styles/DTFormat.tsx
=> Added some tests

Car/__tests__/activity/messages/Chat-test.tsx, Car/package-lock.json, Car/package.json, Car/src/activity/messages/messages-activity/chat/Chat.tsx, Car/src/activity/messages/messages-activity/chat/ChatStyle.tsx, Car/tsconfig.json, Car/yarn.lock
Reverts ita-social-projects/Car-Front-End#514
=> Revert "Revert "424 chat header disapears while texting""

Car/android/settings.gradle
Use npm install to avoid errors
=> Library keyboard adjust has been added

Car/__tests__/components/ApplicationAnswer-test.tsx, Car/android/app/build.gradle, Car/android/app/google-services.json, Car/android/app/src/main/AndroidManifest.xml, Car/android/app/src/main/java/com/car/Entities/Chat.kt, Car/android/app/src/main/java/com/car/Entities/Message.kt, Car/android/app/src/main/java/com/car/Entities/User.kt, Car/android/app/src/main/java/com/car/MainActivity.kt, Car/android/app/src/main/java/com/car/MainApplication.kt, Car/android/app/src/main/java/com/car/NotificationModule/NotificationModule.kt, Car/android/app/src/main/java/com/car/NotificationModule/NotificationPackage.kt, Car/android/app/src/main/java/com/car/NotificationService.kt, Car/src/components/notifications/notifications-types/ApplicationAnswer.tsx
Closes /ita-social-projects/Car-Back-End/issues/239
=> Fix app recognizing as a game

Car/src/components/notifications/notification-ride-details/NotificationRideDetails.tsx, Car/src/components/notifications/notifications-types/ApplicationApproval.tsx
Closes ita-social-projects/Car-Back-End#617
=> Fix the notifications

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx
Closes  ita-social-projects/Car-Back-End#659
=> Fixed editing the ride

Car/api-service/chat-service/ChatService.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx
Closes  ita-social-projects/Car-Back-End#674
=> Changed text for min count of characters

Car/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx
Closes  ita-social-projects/Car-Back-End#676
=> Changed title when car is invalid to delete

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx
Closes ita-social-projects/Car-Back-End#687
=> 687 save button doesn`t work correctly

Car/src/activity/messages/Messages.tsx
Closes ita-social-projects/Car-Back-End/issues/688
=> Trim searching text in chats page

Car/__tests__/activity/my-profile/AppSettings-test.tsx, Car/__tests__/activity/my-profile/Settings-test.tsx, Car/__tests__/activity/my-profile/SettingsTabs-test.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx, Car/src/activity/my-profile/my-profile-activity/settings/settings-activity/app-settings/AppSettings.tsx, Car/src/activity/my-profile/my-profile-activity/settings/settings-activity/app-settings/AppSettingsStyle.tsx, Car/src/activity/my-profile/my-profile-activity/settings/settings-activity/app-settings/app-settings-activity/HelpCenter.tsx, Car/src/activity/my-profile/my-profile-activity/settings/settings-activity/app-settings/app-settings-activity/Language.tsx, Car/src/activity/my-profile/my-profile-activity/settings/settings-activity/app-settings/app-settings-activity/Payment.tsx, Car/src/activity/my-profile/my-profile-activity/settings/settings-tabs/SettingsTabs.tsx, Car/src/components/choose-opton/ChooseOption.tsx, Car/src/components/choose-opton/ChooseOptionProps.tsx, Car/src/components/choose-opton/ChooseOptionStyle.tsx
Closes ita-social-projects/Car-Back-End#689
=> 689 app settings page

Car/src/components/notifications/ConfigPushNotifications.tsx
Closes ita-social-projects/Car-Back-End/issues/695
=> Navigate user from push notifications

Car/__tests__/api-service/UserService-test.tsx, Car/api-service/user-service/UserService.tsx, Car/src/components/auth/AuthProvider.tsx, Car/src/components/header-logout-button/HeaderLogoutButton.tsx
Closes ita-social-projects/Car-Back-End/issues/685
=> Change user's FCMToken managing

Car/__tests__/activity/journey/SearchJourney-test.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx, Car/src/components/address-input-button/AddressInputButton.tsx, Car/src/components/datetime-picker/TouchableDateTimePickerStyle.tsx, Car/src/components/dropdown-picker/JourneyCreationDropDownPickerStyle.tsx
Closes  ita-social-projects/Car-Back-End#691
=> Fixed some styles in journey search/create

Car/__tests__/components/ApplicationRejection-test.tsx, Car/src/components/notifications/notifications-types/ApplicationRejection.tsx
Closes  ita-social-projects/Car-Back-End#617
=> Hide unnecessary information about ride

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx
Closes  ita-social-projects/Car-Back-End#704
=> Fixed save car button

Car/__tests__/components/ApplicationAnswer-test.tsx, Car/__tests__/components/ApplicationRejection-test.tsx, Car/__tests__/components/JourneyNewApplicant-test.tsx, Car/__tests__/components/JourneyNewApplicantView-test.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/components/notifications/NotificationProps.tsx, Car/src/components/notifications/notifications-types/ApplicationAnswer.tsx
Closes  ita-social-projects/Car-Back-End#700
=> Different pages have different stops view

Car/__tests__/activity/journey/JourneyTabs-test.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx, Car/src/components/notifications/notifications-types/ApplicationAnswer.tsx
Closes ita-social-projects/Car-Back-End#723
=> Remove elliptical menu in the chat

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCarsStyle.tsx, Car/src/components/notifications/notifications-types/ApplicationAnswer.tsx
Closes ita-social-projects/Car-Back-End#724
Closes ita-social-projects/Car-Back-End#728
=> 724 drop down list do not work

Car/__tests__/activity/journey/JourneyStartPage-test.tsx, Car/src/activity/journey/JourneyStartPage.tsx, Car/src/activity/journey/JourneyStartPageStyle.tsx, Car/src/activity/messages/Messages.tsx, Car/src/components/badge/BadgeStyle.tsx, Car/src/components/notifications/notifications-types/ApplicationAnswer.tsx, Car/yarn.lock
[Ride Homepage] List of agreed trips has a different implementation when opening 'Ride' page #722
=> Change buttons under manage rides

Car/__tests__/components/HeaderLogoutButton-test.tsx, Car/src/components/confirm-modal/ConfirmModalStyle.tsx
Closes ita-social-projects/Car-Back-End#504
=> Fixed confirm button alignment

Car/src/components/journey-new-applicant/journey-new-applicant-view/JourneyNewApplicantView.tsx, Car/src/components/journey-new-applicant/route-view/RouteView.tsx, Car/src/components/notifications/notifications-types/JourneyCancellation.tsx, Car/src/components/notifications/notifications-types/JourneyInvitation.tsx, Car/src/components/notifications/notifications-types/PassengerWithdrawal.tsx
Closes ita-social-projects/Car-Back-End#741
=> Fixed code smells

Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx
Closes ita-social-projects/Car-Back-End/issues/736
=> Change toggle labels in preferences

Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx, Car/src/components/address-input/AddressInputStyles.tsx, Car/src/constants/GeneralConstants.tsx
Closes ita-social-projects/Car-Back-End/issues/740
=> Add scroll in adress input places

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx, Car/src/components/car-text-input/CarTextInput.tsx
Closes ita-social-projects/Car-Back-End/issues/756
=> Change validation function for pate number

Car/__tests__/components/JourneyNewApplicantView-test.tsx, Car/src/components/journey-new-applicant/journey-new-applicant-view/JourneyNewApplicantView.tsx, Car/src/components/notifications/notification-buttons/NotificationConfirmButton.tsx, Car/src/components/notifications/notification-buttons/NotificationDeclineButton.tsx
Closes ita-social-projects/Car-Back-End#690
=> Fixed bug with accepting new applicant after ride ended

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/notifications/Notifications.tsx
Closes ita-social-projects/Car-Back-End#763
=> Fixed bug with unread notifications

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/journey-page/blocks/send-request-modal/SendRequestModal.tsx, Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx, Car/src/components/commentBlock/CommentBlock.tsx, Car/src/components/commentBlock/CommentBlockProps.tsx, Car/src/components/commentBlock/CommentBlockStyle.tsx
Closes ita-social-projects/Car-Back-End#771
=> Moved comment block to component

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx
#ita-social-projects/Car-Back-End/issues/790
=> Fixed bug with Paid fee is chosen by default

Car/__tests__/components/CarDropDownPicker-test.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
#ita-social-projects/Car-Back-End/issues/829
=> Fixed bug with Ellipsis menu is not shown after returning from 'Ride details' page

Car/src/activity/journey/journey-activity/journey-invitations/JourneyInvitationsPage.tsx
#ita-social-projects/Car-Back-End/issues/817
=> Fixed bug with User can invite himself on his trip

Car/src/components/commentBlock/CommentBlock.tsx
#ita-social-projects/Car-Back-End/issues/798
=> Refixed bug where 'Comments' edit box were empty by default

Car/src/components/save-location-button/SaveLocationButton.tsx
#ita-social-projects/Car-Back-End/issues/843
=> Fixed bug "Send" button doesn`t correspond mock up

Car/__tests__/components/JourneyNewApplicantView-test.tsx, Car/api-service/journey-service/JourneyService.tsx, Car/api-service/notifications-service/NotificationsService.tsx, Car/models/stop/Stop.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/blocks/stops-block/StopsBlock.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx, Car/src/activity/notifications/Notifications.tsx, Car/src/components/journey-new-applicant/journey-new-applicant-view/JourneyNewApplicantView.tsx, Car/src/components/notifications/notifications-types/PassengerWithdrawal.tsx, Car/src/utils/LocationHelperFunctions.tsx
Closes ita-social-projects/Car-Back-End/issues/739
Closes ita-social-projects/Car-Back-End/issues/707
=> Fixed stops names in notifications

Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
#ita-social-projects/Car-Back-End/issues/828
=> Fixed bug with 'Passengers' drop-down value changes to '1' from '4' after searching for a ride

Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
#ita-social-projects/Car-Back-End/issues/839
=> Fixed bug with Opened ellipses menu in 'Add a Ride' page

Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx, Car/src/components/car-text-input/CarTextInput.tsx, Car/src/components/car-text-input/CarTextInputProps.ts
#ita-social-projects/Car-Back-End/issues/846
=> Fixed bug where all borders must become red color when error appears

Car/src/activity/journey/journey-activity/create-journey/CreateJourneyStyle.tsx, Car/src/activity/journey/journey-activity/journey-invitations/JourneyInvitationsPage.tsx, Car/src/activity/journey/journey-activity/journey-invitations/JourneyInvitationsPageStyle.tsx
Fixes ita-social-projects/Car-Back-End#817
=> Added error message under the field 'New invitation' and a few UI changes

Car/src/activity/messages/Messages.tsx, Car/src/activity/messages/messages-activity/chat/Chat.tsx, Car/src/components/car-text-input/CarTextInput.tsx, Car/src/components/input-spinner/SeatsInputSpinner.tsx
Fixes #ita-social-projects/Car-Back-End/issues/854
=>  Inform message from Chats moved to personal chat

Car/src/activity/journey/journey-activity/journey-page/blocks/stops-block/StopsBlock.tsx, Car/src/components/notifications/notifications-types/JourneyInvitation.tsx
Fixes /ita-social-projects/Car-Back-End/issues/865
=> #865 Fixes color of driver's stops in invitation notification

Car/src/activity/journey/journey-activity/create-journey/CreateJourneyStyle.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx
https://github.com/ita-social-projects/Car-Back-End/issues/831
=> -re-fix-bug/831

Car/__tests__/activity/my-profile/CarTabs-test.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx, Car/src/components/SwitchSelector/SwitchSelector.tsx
Fixes ita-social-projects/Car-Back-End/issues/866
=> Fixed bug with 'Edit Car Info' label

Car/__tests__/activity/journey/JourneyTabs-test.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
https://github.com/ita-social-projects/Car-Back-End/issues/875
=> re-fix-bug-875

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx
Closes ita-social-projects/Car-Back-End#863
=> Fixed bug with Fee changes from 'Paid' to 'Free' after publishing a ride with 'Paid' fee

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/journey-invitations/JourneyInvitationsPage.tsx, Car/src/activity/journey/journey-activity/journey-invitations/JourneyInvitationsPageStyle.tsx, Car/src/components/SwitchSelector/SwitchSelector.tsx
Closes ita-social-projects/Car-Back-End/issues/817
This changes were not pushed by pull request ita-social-projects/Car-Front-End/pull/665 because I somehow linked two branches and when I reverted this changes in another branch, it reverts here ita-social-projects/Car-Front-End/pull/665 too
=> Added Error message under the new invitation field

Car/models/journey/PublishRideFilter.tsx, Car/models/journey/RideType.tsx, Car/src/activity/journey/JourneyStartPage.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/components/car-text-input/CarTextInput.tsx, Car/src/components/input-spinner/SeatsInputSpinner.tsx
Closes ita-social-projects/Car-Back-End#861
=> Fixed bug that System doesnt save input state in any editbox in 'Publish a Ride' page

Car/src/components/notifications/notifications-types/JourneyInvitation.tsx
Closes ita-social-projects/Car-Back-End/issues/824
=> Fix journey invitation modal on adding failure

Car/__tests__/activity/journey/JourneyPage-test.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPageStyle.tsx, Car/src/activity/journey/journey-activity/journey-page/blocks/button-block/ButtonBlock.tsx, Car/src/components/commentBlock/CommentBlock.tsx, Car/src/components/commentBlock/CommentBlockProps.tsx
Closes ita-social-projects/Car-Back-End/issues/840
=> Fix send request view

Car/__tests__/activity/journey/JourneyPage-test.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/blocks/send-request-modal/SendRequestModal.tsx
https://github.com/ita-social-projects/Car-Front-End/pull/713
=> re-fix bug/801

Car/__tests__/components/HeaderLogoutButton-test.tsx, Car/models/journey/PublishRideFilter.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourneyStyle.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx
Fixes ita-social-projects/Car-Back-End#861
=> Fixed bug with unsaved invitations, also Fee and Ride type were default after two times going back and forth

Car/__tests__/activity/journey/JourneyTabs-test.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx
Closes ita-social-projects/Car-Back-End#884
=> Fixed bug with default passengers count when user has no cars

Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
Closes ita-social-projects/Car-Back-End#869
=> Added pop-up window at 'Add a Ride' page

Car/__tests__/components/HeaderLogoutButton-test.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourneyStyle.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/components/notifications/notifications-types/JourneyInvitation.tsx
Closes ita-social-projects/Car-Back-End#887
=> Fixed bug with 'Invitation is accepted' pop-up disappears automatically

Car/__tests__/activity/journey/JourneyTabs-test.tsx, Car/__tests__/activity/journey/OkSearchResult-test.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx, Car/src/activity/journey/journey-activity/search-journey/search-results/ok-search-result/OkSearchResult.tsx, Car/src/activity/journey/journey-activity/search-journey/search-results/ok-search-result/OkSearchResultProps.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
Fixes #ita-social-projects/Car-Back-End/issues/13
Added new functionality to button "With previous filter" according to 2.1.4
=> Add new functionality for button "With previous filters"

Car/src/activity/journey/journey-activity/journey-page/blocks/button-block/ButtonBlock.tsx
Fixed ita-social-projects/Car-Back-End/issues/892
=> Fixed bug where Message to all button was not correspond to mock-up

Car/src/components/confirm-modal/ConfirmModal.tsx
Closes #ita-social-projects/Car-Back-End/issues/897
=> Globally changed colors for all pop-ups

Car/__tests__/api-service/ChatService-test.tsx, Car/__tests__/api-service/JourneyService-test.tsx, Car/__tests__/components/JourneyCardList-test.tsx, Car/api-service/chat-service/ChatService.tsx, Car/models/Chat/Chat.tsx, Car/models/journey/Journey.tsx, Car/models/journey/JourneyDto.ts, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx, Car/src/activity/messages/Messages.tsx
/ita-social-projects/Car-Back-End/issues/871
=> Added, when user created a schedule journey, one chat is created for all journey #871

Car/src/components/commentBlock/CommentBlock.tsx
https://github.com/ita-social-projects/Car-Back-End/issues/900
=> fix of preferences page crash

Car/__tests__/activity/journey/OkSearchResult-test.tsx, Car/src/activity/journey/journey-activity/search-journey/search-results/ok-search-result/OkSearchResult.tsx, Car/src/components/navigation/Navigation.tsx
Closes #ita-social-projects/Car-Back-End/issues/881
=> Button "with new filters" open "Search a ride"

Car/src/activity/journey/journey-activity/journey-page/JourneyPageStyle.tsx, Car/src/activity/journey/journey-activity/journey-page/blocks/button-block/ButtonBlock.tsx
Fixed ita-social-projects/Car-Back-End/issues/892
=> Re-fixed bug where Message to all button was not correspond to mock-up

Car/src/activity/journey/journey-activity/journey-page/JourneyPageStyle.tsx
Fixed ita-social-projects/Car-Back-End/issues/903
=> Fixed 'REQUESTED' button style due to mock-up

Car/__tests__/activity/journey/JourneyStartPage-test.tsx, Car/__tests__/components/TouchableNavigationBlock-test.tsx, Car/api-service/APIConfig.tsx, Car/src/activity/journey/JourneyStartPage.tsx, Car/src/activity/journey/JourneyStartPageStyle.tsx, Car/src/components/touchable-navigation-block/TouchableNavigationBlock.tsx, Car/src/components/touchable-navigation-block/TouchableNavigationBlockStyle.tsx
added white border and repair gradient at buttons on start screen, made little tweakes
=> ita-social-projects / Car-Back-End / Bug / 899

Car/models/journey/PublishRideFilter.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
Fixes ita-social-projects/Car-Back-End#861
=> Fixed bug 'schedule a ride' doesn't save state

Car/src/activity/journey/journey-activity/journey-page/blocks/button-block/ButtonBlock.tsx, Car/src/activity/login/Login.tsx, Car/src/components/theme/ThemesColors.tsx
Fixes #ita-social-projects/Car-Back-End/issues/908
=> Fixed button colors and new hover color dark mode

Car/src/activity/my-profile/my-profile-activity/address-book/address-book-tabs/AddressBookTabs.tsx
Fixed ita-social-projects/Car-Back-End/issues/923
=> Fixed bug where error text in modal window did not correspond to story

Car/__tests__/activity/journey/SearchJourney-test.tsx, Car/__tests__/activity/my-profile/Settings-test.tsx, Car/__tests__/components/AvatarLogo-test.tsx, Car/__tests__/components/AvatarLogoTitle-test.tsx, Car/__tests__/components/JourneyCardList-test.tsx, Car/__tests__/components/MinimizedNotification-test.tsx, Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx, Car/src/activity/my-profile/my-profile-activity/settings/SettingsStyle.tsx, Car/src/components/avatar-logo-title/AvatarLogoTitle.tsx, Car/src/components/avatar-logo-title/AvatarLogoTitleStyle.tsx, Car/src/components/avatar-logo/AvatarLogo.tsx, Car/src/components/avatar-logo/AvatarLogoProps.tsx
Closes ita-social-projects/Car-Back-End#922
=> Fixed bug with Settings page does not correspond to the mockup

Car/__tests__/activity/journey/SearchJourney-test.tsx, Car/__tests__/activity/messages/Messages-test.tsx, Car/src/activity/messages/Messages.tsx
/ita-social-projects/Car-Back-End/issues/920
=> Fixed #920, Incorrect text displays when search didn't find anything

Car/__tests__/activity/journey/JourneyPage-test.tsx, Car/__tests__/activity/journey/JourneyStartPage-test.tsx, Car/__tests__/activity/journey/OkSearchResult-test.tsx, Car/__tests__/components/JourneyCard-test.tsx, Car/src/activity/journey/JourneyStartPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPageProps.tsx, Car/src/activity/journey/journey-activity/search-journey/search-results/ok-search-result/OkSearchResult.tsx, Car/src/activity/journey/journey-activity/search-journey/search-results/ok-search-result/OkSearchResultProps.tsx, Car/src/components/journey-card/JourneyCard.tsx, Car/src/components/journey-card/JourneyCardList.tsx
/ita-social-projects/Car-Back-End/issues/925
=> Fixed #925. Ellipses menu presents in past rides

Car/__tests__/activity/journey/SearchJourney-test.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/blocks/stops-block/StopsBlock.tsx, Car/src/constants/GeneralConstants.tsx, Car/src/utils/JourneyHelperFunctions.tsx
closes ita-social-projects/Car-Back-End/issues/901
=> Only passenger stops are displayed if drivers stops are same

Car/__tests__/components/AvatarLogo-test.tsx, Car/__tests__/components/JourneyCardList-test.tsx, Car/src/components/address-input/AddressInput.tsx
Fixed ita-social-projects/Car-Back-End/issues/909
=> Fixed bug where address displays twice in address list

Car/__tests__/api-service/ChatService-test.tsx, Car/__tests__/api-service/JourneyService-test.tsx, Car/__tests__/api-service/ReceivedMessagesService-test.tsx, Car/__tests__/api-service/UserService-test.tsx, Car/__tests__/components/AvatarLogo-test.tsx, Car/__tests__/components/JourneyCardList-test.tsx, Car/__tests__/utils/JourneyHelperFunctions-test.tsx
Fully cover User, Chat, Journey, RecievedMessages services. Tests for few journey helper functions.
closes ita-social-projects/Car-Back-End/issues/927
=> Tests for API-services and journey helper functions

Car/android/app/src/main/AndroidManifest.xml
=> Map credentials update

Car/__tests__/activity/my-profile/AddressBookTabs-test.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-activity/add-locations/AddLocation.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/address-book-tabs/AddressBookTabs.tsx, Car/src/components/location-drop-down-picker/LocationDropDownPicker.tsx
Closes ita-social-projects/Car-Back-End#950
=> Fixed bug with The design of the 'Add Address' page does not correspond to the mock-up

Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsModals.tsx, Car/src/activity/journey/journey-activity/journey-details-page/JourneyDetailsPage.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx
/ita-social-projects/Car-Back-End/issues/943
=> Fixed #943. Pop-up "You have already made a trip within this time!", when try add journey with existing departure time

Car/__tests__/activity/journey/SearchJourney-test.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx, Car/src/components/datetime-picker/TouchableDateTimePicker.tsx, Car/src/components/datetime-picker/TouchableDateTimePickerStyle.tsx
Fixed ita-social-projects/Car-Back-End/issues/939
=> Fixed the design of 'Find a Ride' page

Car/__tests__/activity/journey/CreateJourney-test.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx
Fixed ita-social-projects/Car-Back-End/issues/934
=> Correct position for "Confirm" button

Car/src/activity/messages/Messages.tsx, Car/src/activity/my-profile/my-profile-activity/cars/car-activity/add-edit-cars/AddEditCars.tsx, Car/src/components/avatar-logo/AvatarLogo.tsx, Car/src/components/navigation/app-tabs/AppTabs.tsx
ita-social-projects/Car-Back-End#952
=> Eliminated code smells from frontend part

Car/__tests__/components/AppTabs-test.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/AddressBook.tsx, Car/src/activity/my-profile/my-profile-activity/address-book/AddressBookStyle.tsx, Car/src/components/navigation/app-tabs/AppTabs.tsx
Closes ita-social-projects/Car-Back-End#949
=> Fixed bug with The design of the 'Address Book' page does not correspond to the mock-up

Car/__tests__/activity/notifications/NotificationsTabs-test.tsx, Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/notifications/notifications-tabs/NotificationsTabs.tsx
Closes ita-social-projects/Car-Back-End/issues/947
=> Headers are displeyd at the "Notification" page 

Car/src/activity/journey/journey-activity/journey-page/JourneyPage.tsx, Car/src/activity/journey/journey-activity/journey-page/blocks/button-block/ButtonBlock.tsx
Fixed ita-social-projects/Car-Back-End/issues/954
=> Fixed bug where 'Next' and 'Send Request' buttons did not correspond to mock-up

Car/__tests__/activity/journey/CreateJourney-test.tsx, Car/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx, Car/src/components/styles/HeaderStyle.tsx
Fixes ita-social-projects/Car-Back-End#934
=> Fixed bug with the 'Confirm' button is overlapped with the footer

Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
Fixed ita-social-projects/Car-Back-End/issues/938
=> made changes on filterRecentAddresses function

Car/__tests__/activity/journey/SearchJourney-test.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx, Car/src/activity/journey/journey-activity/search-journey/SearchJourneyStyle.tsx
Fixed ita-social-projects/Car-Back-End/issues/939
=> Fixed button position on 'find a ride' page
